#!/usr/bin/env python3
import json, html, pathlib, datetime
root = pathlib.Path(__file__).resolve().parents[1]
topics = json.loads((root / 'topics/topics.json').read_text())
data = json.loads((root / 'data/items.json').read_text())
items = data.get('items', [])
by_topic = {t['id']: [] for t in topics}
for item in items:
    by_topic.setdefault(item.get('topic', 'other'), []).append(item)
updated = data.get('updatedAt') or datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'
css = '''
:root{color-scheme:light dark;--bg:#0f1115;--card:#171a21;--text:#e9edf3;--muted:#9aa4b2;--accent:#ff7a59;--line:#2a2f3a}body{margin:0;font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}main{max-width:980px;margin:0 auto;padding:40px 20px 80px}header{margin-bottom:28px}.brand{display:flex;align-items:center;gap:12px}h1{font-size:34px;margin:0}p{margin:8px 0;color:var(--muted)}.topic{margin:28px 0}.topic h2{border-bottom:1px solid var(--line);padding-bottom:8px}.item{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px 18px;margin:14px 0}.item h3{margin:0 0 6px;font-size:18px}.meta{font-size:13px;color:var(--muted)}.summary{color:var(--text)}.note{border-left:3px solid var(--accent);padding-left:10px}.tag{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:1px 8px;font-size:12px;color:var(--muted)}a{color:#8ab4ff}.empty{color:var(--muted);font-style:italic}footer{margin-top:40px;color:var(--muted);font-size:13px}
'''
parts = [f'''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Longxia Info Board</title><style>{css}</style></head><body><main><header><div class="brand"><div style="font-size:42px">🦞</div><div><h1>Longxia Info Board</h1><p>自動搜尋、整理、去重的資訊看板。最後更新：{html.escape(updated)}</p></div></div></header>''']
for topic in topics:
    tid = topic['id']; name = topic['name']; rows = by_topic.get(tid, [])
    parts.append(f'<section class="topic" id="{html.escape(tid)}"><h2>{html.escape(name)}</h2>')
    if not rows:
        parts.append('<p class="empty">尚無資料，下一次自動更新後會出現。</p>')
    for item in rows[:20]:
        title = html.escape(item.get('title') or '(untitled)')
        url = html.escape(item.get('url') or '#')
        date = html.escape(item.get('published') or item.get('foundAt') or '')
        source = html.escape(item.get('source') or '')
        summary = html.escape(item.get('summary') or '')
        note = html.escape(item.get('longxiaNote') or '')
        importance = html.escape(item.get('importance') or 'medium')
        parts.append(f'<article class="item"><h3><a href="{url}" rel="noopener noreferrer">{title}</a></h3><div class="meta">{date} · {source} · <span class="tag">{importance}</span></div><p class="summary">{summary}</p>')
        if note: parts.append(f'<p class="note">{note}</p>')
        parts.append('</article>')
    parts.append('</section>')
parts.append('<footer>Generated by Longxia 🦞. Sources are linked to original publishers.</footer></main></body></html>')
(root / 'docs/index.html').write_text('\n'.join(parts))
